---
- name: Restart elasticsearch
  service:
    name: elasticsearch
    state: restarted

- name: Restart kibana
  service:
    name: kibana
    state: restarted

- name: Restart apm-server
  service:
    name: apm-server
    state: restarted
