# Copyright:: Copyright (c) 2014 eGlobalTech, Inc., all rights reserved
#
# Licensed under the BSD-3 license (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License in the root of the project or at
#
#     http://egt-labs.com/mu/LICENSE.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"
gemspec :path => "../", :name => "cloud-mu"
gem 'berkshelf', '= 8.0.9'
gem 'net-smtp'
gem 'archive-tar-minitar'
gem 'mysql2', '<= 0.5.2'
gem 'ruby-wmi'
gem 'chef-vault', "~> 3.4"
gem 'chef-sugar'
gem 'ffi-libarchive' # needed to keep berkshelf from breaking on Mac tarballs
gem 'knife-windows', :git => "https://github.com/eGT-Labs/knife-windows.git", :branch => "winrm_cert_auth"
gem 'foodcritic', '~> 14.1.0'
gem 'chef', '~> 18.7.6'
gem 'knife', '~> 18.6.13'
gem 'ed25519', '>= 1.2', '< 2.0'
gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'

gem 'rack'#, "~> 2.0"
gem 'winrm', "~> 2.3", ">= 2.3.4"
gem 'thin'#, "~> 1.7"

gem "aws-sdk-core", "~> 3.214.0"
gem "aws-sdk", "~> 3.2"
gem 'google-api-client', "~> 0.53.0"
gem 'googleauth'
#  s.add_runtime_dependency 'azure_sdk', '~> 0.65'
