# Copyright:: Copyright (c) 2014 eGlobalTech, Inc., all rights reserved
#
# Licensed under the BSD-3 license (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License in the root of the project or at
#
#     http://egt-labs.com/mu/LICENSE.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"
gem 'yard'
gem 'ruby-graphviz', "~> 1.2.3"
gem 'chef', "~> 12.21.31"
gem 'chef-zero', "< 13"
gem "aws-sdk-core", "~> 2.6.42"
gem 'simple-password-gen'
gem 'trollop', "~> 2.1.2"
gem 'json-schema'
gem 'colorize'
gem 'color'
gem 'rack'
gem 'thin'
gem 'berkshelf', '~> 6.3.1'
gem 'pg', '< 1.0'
gem 'mysql'
gem 'ruby-wmi'
gem 'chef-vault', "< 3"
gem 'net-ssh', "~> 3.2.0"
gem 'netaddr', '< 2.0'
gem 'nokogiri', "~> 1.8.2"
gem 'solve', '>= 3.1.1'
gem 'net-ldap'
gem 'googleauth'
gem 'google-api-client', '~> 0.19.7'
gem 'chef-sugar'
gem 'winrm', '= 2.2.3'
gem 'knife-windows', :git => "https://github.com/eGT-Labs/knife-windows.git", :branch => "winrm_cert_auth"
gem 'rubocop', '= 0.52.1'
gem 'foodcritic', '= 12.3.0'
#gem 'inspec', '<~ 1.51.18'
