# Copyright:: Copyright (c) 2014 eGlobalTech, Inc., all rights reserved
#
# Licensed under the BSD-3 license (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License in the root of the project or at
#
#     http://egt-labs.com/mu/LICENSE.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"
gem 'yard'
gem 'ruby-graphviz', "~> 1.2.2"
gem 'chef', "~> 12.16.42"
gem "aws-sdk-core", "~> 2.6.28"
gem 'simple-password-gen'
gem 'trollop', "~> 2.1.2"
gem 'knife-windows', '1.4.0'
gem 'fileutils'
gem 'json-schema'
gem 'colorize'
gem 'color'
gem 'rack'
gem 'thin'
gem 'berkshelf'
gem 'pg'
gem 'mysql'
gem 'ruby-wmi'
gem 'chef-vault', "~> 2.9.0"
gem 'net-ssh', "~> 3.2.0"
gem 'netaddr'
gem 'nokogiri', "~> 1.6.8"
gem 'net-ldap'
