---
- name: Install all updates with automatic reboots
  win_updates:
    reboot: yes
    reboot_timeout: 1800

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Install ruby
  win_chocolatey:
    name: ruby
    state: present

- name: Install openssh
  win_chocolatey:
    name: openssh
    state: present

- name: "Tell ec2config to set a random password on next boot"
  when: (ansible_facts['distribution'] == "Microsoft Windows Server 2012 R2 Standard" and mu_build_image is defined and mu_build_image == True)
  win_copy:
    src: config.xml
    dest: "c:/Program Files/Amazon/EC2ConfigService/Settings/config.xml"
