---
- name: Install all updates with automatic reboots
  win_updates:
    reboot: yes
    reboot_timeout: 1800

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Install ruby
  win_chocolatey:
    name: ruby
    state: present

- name: Install openssh
  win_chocolatey:
    name: openssh
    state: present
