image: chef/chefdk:latest

stages:
  - Lint
  - Test
  - Merge
  - Deploy
  
Rubocop:
  stage: Lint
  script:
    - rubocop modules/
  allow_failure: true

Cookstyle:
  stage: Lint
  script:
    - cookstyle cookbooks/
  allow_failure: true
  
Foodcritic:
  stage: Lint
  script:
    - foodcritic cookbooks/
  allow_failure: true

Berks:
  stage: Test
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks install); done
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks verify); done
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks outdated); done
  allow_failure: true
  
Old_Berks:
  stage: Test
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - rm -rf Berksfile.lock
    - berks install
    - berks verify
    - berks outdated
  allow_failure: true

ChefSpec:
  stage: Test
  script:
    - for d in ./cookbooks/*/ ; do (cd "$d" && chef exec rspec); done
  allow_failure: true
