image: centos

stages:
  - Lint Tests
  - Tests
  - Security Tests
  - Smoke Test
  - Merge/Tag
  - Dockerbuild
  - Deploy
  
Rubocop:
  stage: Lint Tests
  image: chef/chefdk:latest
  script:
    - rubocop modules/
    - rubocop bin/
  allow_failure: true

Cookstyle:
  stage: Lint Tests
  image: chef/chefdk:latest
  script:
    - cookstyle cookbooks/
  allow_failure: true
  
Foodcritic:
  stage: Lint Tests
  image: chef/chefdk:latest
  script:
    - foodcritic cookbooks/
  allow_failure: true

ChefSpec:
  stage: Test
  image: chef/chefdk:latest
  script:
    - for d in ./cookbooks/*/ ; do (cd "$d" && chef exec rspec); done
  allow_failure: true

Rspec:
  stage: Test
  image: chef/chefdk:latest
  script:
    - echo "rspec"
  allow_failure: true

.New_Berks:
  stage: Test
  image: chef/chefdk:latest
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks install); done
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks verify); done
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks outdated); done
  
Berks:
  stage: Test
  image: chef/chefdk:latest
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - rm -rf Berksfile.lock
    - berks install
    - berks verify
    - berks outdated

BuildMan:
  stage: Security Tests
  script:
    - echo "BuildMan!"

Smoke_Test:
  stage: Smoke Test
  script:
    - echo "Insert Smoke Stuff Here"
  only:
    - master
    - development
  when: manual

Merge/Tag:
  stage: Merge/Tag
  script:
    - echo "Merge and tag here"
  only:
    - master
    - development

Dockerbuild:
  stage: Dockerbuild
  script:
    - echo "Build Mu Docker Container"
  only:
    - master
    - development

pages:
  stage: Deploy
  image: ruby:2.3
  script:
  - mkdir public
  - gem install yard
  - yard doc modules -m markdown -o public
  artifacts:
    paths:
    - public
  only:
  - master
