image: centos

stages:
  - Lint Test
  - Test
  - Security Test
  - Smoke Test
  - Merge/Tag
  - Dockerbuild
  - Deploy
  
Rubocop:
  stage: Lint Test
  image: chef/chefdk:latest
  script:
    - rubocop modules/
    - rubocop bin/
  allow_failure: true

Cookstyle:
  stage: Lint Test
  image: chef/chefdk:latest
  script:
    - cookstyle cookbooks/
  allow_failure: true
  
Foodcritic:
  stage: Lint Test
  image: chef/chefdk:latest
  script:
    - foodcritic cookbooks/ -t ~FC075 -t ~FC015 -t ~FC034 -t ~FC122
  allow_failure: true

Foodcritic Deprications:
  stage: Lint Test
  image: chef/chefdk:latest
  script:
    - foodcritic cookbooks/ -t depricated -t chef13 -t chef14

ChefSpec:
  stage: Test
  image: chef/chefdk:latest
  script:
    - for d in ./cookbooks/*/ ; do (cd "$d" && chef exec rspec); done
  allow_failure: true

Rspec:
  stage: Test
  image: chef/chefdk:latest
  script:
    - echo "rspec"
  allow_failure: true

.New_Berks:
  stage: Test
  image: chef/chefdk:latest
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks install); done
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks verify); done
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks outdated); done
  
Berks:
  stage: Test
  image: chef/chefdk:latest
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - rm -rf Berksfile.lock
    - berks install
    - berks verify
    - berks outdated

BrakeMan:
  stage: Security Test
  image: codeclimate/codeclimate-brakeman:latest
  script:
    - echo "BrakeMan!"

Parser Test:
  stage: Smoke Test
  script:
    - mu-deploy -d modules/tests/super_simple_bok.yml
    - mu-deploy -d modules/tests/super_complex_bok.yml
  tags: 
    - mu-master

Smoke Test:
  stage: Smoke Test
  script:
    - mu-upload-chef-artifacts -sn
    - mu-deploy /opt/mu/var/demo_platform/applications/gitlab-server.yml -p vpc_id=vpc-040da43493f894a8d
  tags: 
    - mu-master
  only:
    - master
    - development
  when: manual

Merge/Tag:
  stage: Merge/Tag
  script:
    - echo "Merge and tag here"
  only:
    - master
    - development

Dockerbuild:
  stage: Dockerbuild
  image: docker:latest
  script:
    - echo "Build Mu Docker Container"
  only:
    - master
    - development

pages:
  stage: Deploy
  image: ruby:2.3
  script:
  - mkdir public
  - gem install yard
  - yard doc modules -m markdown -o public
  artifacts:
    paths:
    - public
  only:
  - master
