files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - modules/**/*.rb
    - modules/**/**/*.rb
    - modules/**/**/**/*.rb
    #- bin/*
  # define files excluded from the analysis (defaults to [])