source 'https://supermarket.chef.io'
source chef_repo: ".."

metadata

# Mu Cookbooks
cookbook 'mu-master'
cookbook 'mu-utility'
cookbook 'mu-tools'

# Supermarket Cookbooks
cookbook 'java', '~> 2.2.0'
cookbook 'jenkins', '~> 6.2.0'
cookbook 'chef-vault', '~> 3.1.1'