source 'https://supermarket.chef.io'
source :chef_server

cookbook 'mu-utility', path: '../mu-utility'
cookbook 'simple_iptables', '~> 0.8.0'
cookbook 'apache2', '< 4.0'
cookbook 'mysql', '~> 8.5.1'
cookbook 'yum-epel', '~> 3.2.0'