source 'https://supermarket.chef.io'
source chef_repo: ".."

metadata

# Mu Cookbooks
cookbook "nagios"
cookbook "mu-utility"
cookbook "mu-splunk"
cookbook "mu-firewall"
cookbook "mu-activedirectory"

# Supermarket Cookbooks
cookbook "oracle-instantclient", '~> 1.1.0'
cookbook "database", '~> 6.1.1'
cookbook "postgresql", '~> 7.1.0'
cookbook "java", '~> 2.2.0'
cookbook "windows", '~> 5.1.1'
cookbook "chef-vault", '~> 3.1.1'
cookbook "poise-python", '~> 1.7.0'
cookbook "yum-epel", '~> 3.2.0'