driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  - recipe[java]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  - recipe[java]

- name: centos-6.7
  run_list:
  - recipe[yum-epel]
  - recipe[java]
  attributes: {java: {set_etc_environment: true}}

- name: centos-7.1
  run_list:
  - recipe[yum-epel]
  - recipe[java]
  attributes: {java: {install_flavour: openjdk, jdk_version: 7, set_etc_environment: true }}

- name: opscode-opensuse-13.1
  driver:
    box: opensuse-13.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.1-x86_64_chef-provisionerless.box
  attributes: {java: {install_flavour: openjdk, jdk_version: 7, openjdk_packages: [ "java-1_7_0-openjdk", "java-1.7.0-openjdk-devel" ], set_etc_environment: true }}
  run_list:
  - recipe[tomcat::zypper_refresh]
  - recipe[java]

suites:
- name: tomcat6
  data_bags_path: 'test/integration/tomcat6/data_bags'
  run_list: ["recipe[tomcat]", "recipe[tomcat::users]"]
  excludes: ["centos-7.1", "opscode-opensuse-13.1"]
  attributes: {}

- name: tomcat7
  data_bags_path: 'test/integration/tomcat7/data_bags'
  provisioner:
    encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret_key'
  run_list: ["recipe[tomcat]", "recipe[tomcat::users]"]
  excludes: ["centos-6.6"]
  attributes: {tomcat: {base_version: 7}}
