source 'https://supermarket.chef.io'
source chef_repo: ".."

metadata

# Mu Cookbooks

# Supermarket Cookbooks
cookbook "windows", '~> 5.1.1'
cookbook "chef-vault", '~> 3.1.1'
cookbook "yum-epel", '~> 5.0.8'
