---

- name: remove firewalld
  package:
    name: firewalld
    state: absent

- name: make sure iptables is available
  package:
    name: iptables-services
    state: present

- name: allow inbound for internal services
  iptables:
    chain: INPUT
    source: "{{ mu_deployment['vpcs']['wrapper']['ip_block'] }}"
    destination_port: "{{ item }}"
    protocol: tcp
    jump: ACCEPT
  with_items:
  - "9200"
  - "9300"

- name: add yum repo for ElasticSearch
  yum_repository:
    name: elasticsearch
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    description: Elasticsearch repository for 7.x packages

- name: install elasticsearch and related packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - elasticsearch
  - kibana
  - httpd-tools

- name: ElasticSearch config files in /etc/elasticsearch
  copy:
    dest: "/etc/elasticsearch/{{ item }}"
    src: "{{ item }}"
    mode: 0660
    owner: root
    group: elasticsearch
  become: yes
  with_items:
  - jvm.options
  - elasticsearch.yml

- name: Kibana config files in /etc/kibana
  copy:
    dest: "/etc/kibana/{{ item }}"
    src: "{{ item }}"
    mode: 0640
  become: yes
  with_items:
  - kibana.yml

- name: Copy ElasticSearch certificate store into place
  copy:
    dest: "/etc/elasticsearch/{{ item }}"
    src: "/opt/mu/var/ssl/{{ inventory_hostname }}.pfx"
    mode: 0640
    group: elasticsearch
  become: yes
  with_items:
  - elastic-certificates.p12
  - http.p12

- name: "Enable and start ElasticSearch"
  service:
    name: elasticsearch
    state: started
