driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8081}]
    run_list:
    - recipe[apt::default]
  - name: ubuntu-16.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8082}]
    run_list:
    - recipe[apt::default]
  - name: debian-7.11
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8083}]
    run_list:
    - recipe[apt::default]
  - name: debian-8.6
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8084}]
    run_list:
    - recipe[apt::default]
  - name: freebsd-10.3
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8085}]
  - name: freebsd-11.0
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8086}]
  - name: centos-7.3
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8087}]
  - name: centos-6.8
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8088}]
  - name: centos-5.11
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8089}]
  - name: fedora-25
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8090}]
suites:
 - name: server_package
   run_list:
   - recipe[nagios::default]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
 - name: server_source
   run_list:
   - recipe[nagios::default]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
       server:
         install_method: 'source'
 - name: pagerduty
   run_list:
   - recipe[nagios::default]
   - recipe[nagios::pagerduty]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
       server:
         install_method: 'source'
       pagerduty:
         key: 'your_key_here_3eC2'
 - name: allowed_ips
   run_list:
   - recipe[nagios::default]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
       allowed_ips: ['127.0.0.1', '::1']
data_bags_path: test/data_bags
roles_path: test/roles
