<% if $complexity == "complex" %>
name: redis
engine: redis
creation_style: new
size: cache.t2.medium
name: memcache
creation_style: new
engine: memcached
size: cache.t2.medium
<% else %>
name: redis
engine: redis
creation_style: new
size: cache.t2.medium
name: memcache
creation_style: new
engine: memcached
size: cache.t2.medium
<% end %>
