<% if $complexity == "complex" %>
name: k8s
flavor: EKS
instance_type: t2.medium
instance_count: 4
kubernetes:
  max_pods: 10
platform: centos
# This stanza is optional; normal deployments to EKS might be done with kubectl
# or through a CI tool such as GitLab
kubernetes_resources:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-deployment
  spec:
    selector:
      matchLabels:
        app: nginx
    replicas: 2
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.8
          ports:
          - containerPort: 80  
<% else %>
name: ecs
flavor: ECS
instance_type: t2.medium
<% end %>
