<% if complexity == "complex" %>

name: database-complex
size: db.r4.large
engine: postgres
engine_version: 9.6.6
storage: 21
add_cluster_node: true
allow_major_version_upgrade: true
auto_minor_version_upgrade: false
backup_retention_period: 10
cluster_node_count: 2
create_cluster: true
vpc:
  name: <%= vpc_name %>
create_read_replica: true
master_user: Bob
multi_az_on_create: true

<% else %> # IF NOT COMPLEX THEN ASSUME SIMPLE

name: database-simple
vpc:
  name: <%= vpc_name %>
size: <%= db_size %>
engine: mariadb

<% end %>
