<% if complexity == 'complex' %>
name: <%= logs_name %>
filters:
- name: myfilter
  metric_name: LogMetrics/myfilter
  namespace: ok
  search_pattern: failed
  value: yes
<% else %>
name: <%= logs_name %>
<% end %>
