<% if complexity == 'complex' %>
name: servercomplex
size: <%= instance_type %>
vpc:
  name: <%= vpc_name %>
<% else %>
name: serversimple
size: <%= instance_type %>
vpc:
  name: <%= vpc_name %>
<% end %>
