#!/bin/sh
#
# Fix permissions that Git and our standard umask tend to stomp.

if [ "`whoami`" == "root" ];then
	scriptpath="`dirname $0`"
	# XXX dumbly assume we're in Mu's LIBDIR in .git/hooks
	library=1
	source "`dirname $0`"/../../install/deprecated-bash-library.sh
	set_permissions "skip_rubies"
fi
