#!/bin/sh
#
# Fix permissions that Git and our standard umask tend to stomp.

if [ "`whoami`" == "root" ];then
  scriptpath="`dirname $0`"
  library=1
  # XXX dumbly depend on this old shell lib
  # XXX dumbly assume we're in Mu's LIBDIR in .git/hooks
  source "$scriptpath/../../install/deprecated-bash-library.sh"
  set_permissions "skip_rubies"
fi
